name: Env Docker Image CI

on:
  push:
    branches:    
    - master  
    paths:
    - 'Dockerfile'
    - '.github/workflows/dockerimage.yml'
  schedule:
    - cron:  '0 2 * * *'

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/gumlooter/lab/jupyter
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        registry: docker.pkg.github.com
        snapshot: true
